CREATE TABLE guru (
  id_guru SERIAL PRIMARY KEY,
  nama_guru VARCHAR(100) NOT NULL,
  nip VARCHAR(30) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE guru
ADD COLUMN mapel JSONB NOT NULL DEFAULT '[]';
